language: node_js
node_js:
  - 8
os:
  - osx

git:
  depth: 3
branches:
  only:
    - /^v.*$/

cache:
  directories:
    - node_modules
    - ~/Library/Caches/electron

install:
  - npm install
script:
  - npm run make
after_success:
  - ls out/make

deploy:
  provider: releases
  api_key:
    secure: ${GITHUB_TOKEN}
  target_commitish: ${TRAVIS_COMMIT}
  tag_name: ${TRAVIS_TAG}
  name: Bidream-${TRAVIS_TAG}
  body: Automated release from Travis CI with added files from AppVeyor build
  file_glob: true
  file: out/make/*.dmg
  overwrite: true
  draft: true
  skip_cleanup: true
  on:
    tags: true