language: node_js
node_js:
  - 8
os:
  - osx

git:
  depth: 3
branches:
  only: master

cache:
  directories:
    - node_modules
    - ~/Library/Caches/electron

install:
  - npm install
script:
  - npm run make
after_success:
  - ls out/make

deploy:
  provider: releases
  api_key:
    secure: ${GITHUB_TOKEN}
  file_glob: true
  file: out/make/*.dmg 
  skip_cleanup: true
  on:
    tags: true